version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"  # Pour prediction_service
      - "8001:8001"  # Pour performance_service
    volumes:
      - .:/app  # Monte le répertoire actuel dans le conteneur

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"  # Expose le port du frontend
    volumes:
      - .:/app  # Monte le répertoire actuel dans le conteneur
    depends_on:
      - backend  # Le frontend dépend du backend