# Utilise une image de base Python
FROM python:3.9-slim

# Définit le répertoire de travail
WORKDIR /app

# Copie les fichiers nécessaires
COPY requirements.txt .
COPY . .

# Installe les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Expose les ports pour les services
EXPOSE 8000  
EXPOSE 8001 

# Copie le script de démarrage
COPY start_service.sh /app/start_service.sh
RUN chmod +x /app/start_service.sh

# Commande pour lancer les deux services
CMD ["./start_service.sh"]