# Utilise une image de base Node.js
FROM node:16

# Définit le répertoire de travail
WORKDIR /app

# Copie les fichiers nécessaires
COPY package.json package-lock.json ./

# Copie le reste des fichiers
COPY . .

# Expose le port (Vite utilise 5173 par défaut)
EXPOSE 5173

# Commande pour lancer le frontend
CMD ["npm", "run", "dev"]